# Generated by Django 4.2.24 on 2025-11-10 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predicciones', '0002_comuna_latitud_comuna_longitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloLSTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionLSTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendimiento_predicho_ano_actual', models.FloatField()),
                ('confianza', models.FloatField(default=0.85)),
                ('predicciones_10_anos', models.JSONField(default=dict)),
                ('tiene_datos_historicos', models.BooleanField(default=False)),
                ('r2_calibracion', models.FloatField(null=True)),
                ('sesgo_correccion', models.FloatField(null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='predicciones.modelolstm')),
                ('prediccion_original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediccion_lstm', to='predicciones.prediccion')),
            ],
        ),
        migrations.CreateModel(
            name='DatosPredioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('rendimiento_real', models.FloatField()),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('prediccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicciones.prediccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'prediccion', 'ano')},
            },
        ),
    ]
