# Generated by Django 4.2.24 on 2025-11-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0003_modelolstm_prediccionlstm_datosprediohistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelolstm',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='modelolstm',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='modelolstm',
            table='predicciones_modelolstm',
        ),
    ]
