# Generated by Django 4.2.24 on 2025-11-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0004_modelolstm_descripcion_alter_modelolstm_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccionlstm',
            name='rendimiento_predicho_ano_actual',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
